POST http://localhost:8080/user/addUser
Content-Type: application/json
Accept: text/html

{
}

###

GET http://localhost:8080/go
Accept: text/html;

###

POST http://localhost:8080/valid/t1
Content-Type: application/json

{
//  "logType": "12312"
  "logType": "21"
}

###
POST http://localhost:8080/valid/t2
Content-Type: application/json

{
  "logType": "1"
}

###